# Import functions
. (Join-Path $PSScriptRoot 'Utils.ps1')
. (Join-Path $PSScriptRoot 'Register-TFArgumentCompleter.ps1')
. (Join-Path $PSScriptRoot 'Find-TFRelease.ps1')
. (Join-Path $PSScriptRoot 'Find-TFVersion.ps1')
. (Join-Path $PSScriptRoot 'Test-TFVersion.ps1')
. (Join-Path $PSScriptRoot 'Get-TFVersionFromFile.ps1')
. (Join-Path $PSScriptRoot 'Save-TFBinary.ps1')
. (Join-Path $PSScriptRoot 'Save-TFLinterBinary.ps1')
. (Join-Path $PSScriptRoot 'Set-TFAlias.ps1')
. (Join-Path $PSScriptRoot 'Get-TFAlias.ps1')
. (Join-Path $PSScriptRoot 'Uninstall-TFAlias.ps1')